### ISSUE TITLE
peer-to-peer code review feedback

### ISSUE THREAD

**Issue by denscholar** [eduardosancho/setup_and_mobile_version_skeleton#12]
### You have done great in your project, and at this point, we have nothing to say other that, keep it up! ♻️ 

<img src="https://media2.giphy.com/media/0UyfYP4LUJU2FM0wOq/giphy.gif"/>

**Comment by hendridg** [comment]
# Absolutely brilliant :fire: :fire: :fire: 

### Great job @eduardosancho keep going

![Approved](https://user-images.githubusercontent.com/22258274/138466108-6b14c541-6a88-44c5-ba76-c64992ac1835.gif)

**Comment by eduardosancho** [comment]
thank you guys, i appreciate it a lot
