### ISSUE TITLE
Code review activity

### ISSUE THREAD

**Issue by sumairq** [eduardosancho/setup_and_mobile_version_skeleton#5]
As a group, we will be reviewing the latest pull request

**Comment by sumairq** [comment]
#4 I would recommend watching a mosaic layout youtube video in order to fix the layout issues.

**Comment by eduardosancho** [comment]
Will look into that, thank you :star:

**Comment by Yothu** [comment]
I would recommend looking for the smallest horizontal and vertical elements in the project section, and creating the grid container based on its size, and positioning the rest of the elements in it. If it doesn't work or it takes too much time, I think it would be best to switch templates.

**Comment by fbclh** [comment]
* My partner is doing the same template as you and he managed to do what are you trying to do. I will put you in contact with him.
* Talk to them first explaining the problem first before in case you need to switch template, I am sure they will be fine with that.
